package com.example.delhimetronavigationapp



// Create metro data with 15 stations, 4 lines, and 3 interchanges
fun createMetroData(): Pair<List<Station>, List<Connection>> {
    val stations = listOf(


//        Yellow line

        Station("S1", "Samaypur Badli", listOf("Yellow")),
        Station("S2", "Rohini Sector - 18", listOf("Yellow")),
        Station("S3", "Haiderpur Badli Mor", listOf("Yellow")),
        Station("S4", "Jahangirpuri", listOf("Yellow")),
        Station("S5", "Adarsh Nagar", listOf("Yellow")),
        Station("S6", "Azadpur", listOf("Yellow","Pink")),
        Station("S7", "Model Town", listOf("Yellow")),
        Station("S8", "G.T.B Nagar", listOf("Yellow")),
        Station("S9", "Vishwavidyalaya", listOf("Yellow")),
        Station("S10", "Vidhan Sabha", listOf("Yellow")),
        Station("S11", "Civil Lines", listOf("Yellow")),
        Station("S12", "Kashmere Gate", listOf("Yellow","Red","Violet")),
        Station("S13", "Chandni Chowk", listOf("Yellow")),
        Station("S14", "Chawri Bazar", listOf("Yellow")),
        Station("S15", "New Delhi", listOf("Yellow")),
        Station("S16", "Rajiv Chowk", listOf("Yellow","Blue")),
        Station("S17", "Patel Chowk", listOf("Yellow")),
        Station("S18", "Central Secretariate", listOf("Yellow","Violet")),
        Station("S19", "Udyog Bhawan", listOf("Yellow")),
        Station("S20", "Lok kalyan Marg", listOf("Yellow")),
        Station("S21","Jor Bagh", listOf("Yellow")),
        Station("S22","Dilli Haat - INA", listOf("Yellow","Pink")),
        Station("S23", "AIIMS", listOf("Yellow")),
        Station("S24", "Green Park", listOf("Yellow")),
        Station("S25", "Hauz Khas", listOf("Yellow","Mergenta")),
        Station("S26", "Malviya Nagar", listOf("Yellow")),
        Station("S27", "Saket", listOf("Yellow")),
        Station("S28", "Qutub Minar", listOf("Yellow")),
        Station("S29", "Chhattarpur", listOf("Yellow")),
        Station("S30", "SultanPur", listOf("Yellow")),
        Station("S31", "Ghitorni", listOf("Yellow")),
        Station("S32", "Arjangarh", listOf("Yellow")),
        Station("S33", "Guru Dronacharya", listOf("Yellow")),
        Station("S34", "Sikanderpur", listOf("Yellow")),
        Station("S35", "M G Road", listOf("Yellow")),
        Station("S36", "IFFCO Chowk", listOf("Yellow")),
        Station("S37", "Millennium City Centre", listOf("Yellow")),




        // Red Line


        Station("S38", "Rithala", listOf("Red")),
        Station("S39", "Rohini West", listOf("Red")),
        Station("S40", "Rohini East", listOf("Red")),
        Station("S41", "Pitampira", listOf("Red")),
        Station("S50", "Kohat Enclave", listOf("Red")),
        Station("S42", "Netaji Subhash Place", listOf("Red","Pink")),
        Station("S43", "Keshav Puram", listOf("Red")),
        Station("S44", "Kanhaiya Nagar", listOf("Red")),
        Station("S45", "Inderlok", listOf("Red","Green")),
        Station("S46", "Shastri Nagar", listOf("Red")),
        Station("S47", "Pratap Nagar", listOf("Red")),
        Station("S48", "Pulbangash", listOf("Red")),
        Station("S49", "Tis Hazari", listOf("Red")),
//      "Kashmere Gate"   -> already in yellow line
        Station("S51", "Shastri Park", listOf("Red")),
        Station("S52", "Seelampur", listOf("Red")),
        Station("S53", "Welcome", listOf("Red","Pink")),
        Station("S54", "Shahdara", listOf("Red")),
        Station("S55", "Mansarovar Park", listOf("Red")),
        Station("S56", "Jhilmil", listOf("Red")),
        Station("S57", "Dilshad Garden", listOf("Red")),
        Station("S58", "Shaheed Nagar", listOf("Red")),
        Station("S59", "Rajbagh", listOf("Red")),
        Station("S60", "Major Mohit Sharma Rajender Nagar", listOf("Red")),
        Station("S61", "Shyam Park", listOf("Red")),
        Station("S62", "Mohan Nagar", listOf("Red")),
        Station("S63", "Arthala", listOf("Red")),
        Station("S64", "Hindon River", listOf("Red")),
        Station("S65", "Shaheed Sthal (New Bus Adda)", listOf("Red")),


//      Blue Line

        Station("S66", "Dwarka Sec. 14", listOf("Blue")),
        Station("S67", "Dwarka Sec. 13", listOf("Blue")),
        Station("S68", "Dwarka Sec. 12", listOf("Blue")),
        Station("S218", "Dwarka Sec. 11", listOf("Blue")),
        Station("S219", "Dwarka Sec. 10", listOf("Blue")),
        Station("S220", "Dwarka Sec. 9", listOf("Blue")),
        Station("S221", "Dwarka Sec. 8", listOf("Blue")),
        Station("S222", "Dwarka Sec. 21", listOf("Blue")),

        Station("S69", "Dwarka", listOf("Blue")),
        Station("S70", "Dwarka Mor", listOf("Blue")),
        Station("S71", "Nawada", listOf("Blue")),
        Station("S72", "Uttam Nagar West", listOf("Blue")),
        Station("S73", "Uttam Nagar East", listOf("Blue")),
        Station("S74", "Janakpuri West", listOf("Blue","Mergenta")),
        Station("S75", "Janakpuri East", listOf("Blue")),
        Station("S76", "Tilak Nagar", listOf("Blue")),
        Station("S77", "Subhash Nagar", listOf("Blue")),
        Station("S78", "Tagore Garden", listOf("Blue")),
        Station("S79", "Rajouri Garden", listOf("Blue","Pink")),
        Station("S80", "Ramesh Nagar", listOf("Blue")),
        Station("S81", "Moti Nagar", listOf("Blue")),
        Station("S82", "Kirti Nagar", listOf("Blue","Green")),
        Station("S83", "Shadipur", listOf("Blue")),
        Station("S84", "Patel Nagar", listOf("Blue")),
        Station("S85", "Rajendra Place", listOf("Blue")),
        Station("S86", "Karol Bagh", listOf("Blue")),
        Station("S87", "Jhandewalan", listOf("Blue")),
        Station("S88", "RK Ashram Marg", listOf("Blue")),

        Station("S89", "Barakhamba RD.", listOf("Blue")),
        Station("S90", "Mandi House", listOf("Blue","Violet")),
        Station("S91", "Pragati Maidan", listOf("Blue")),
        Station("S92", "Indraprastha", listOf("Blue")),
        Station("S93", "Yamuna Bank", listOf("Blue")),

        Station("S94", "Akshardham", listOf("Blue")),
        Station("S95", "Mayur Vihar - 1", listOf("Blue","Pink")),
        Station("S96", "Mayur Vihar - 1 EXTN.", listOf("Blue")),
        Station("S97", "New Ashok Nagar", listOf("Blue")),
        Station("S98", "Noida Sec. 15", listOf("Blue")),
        Station("S99", "Noida Sec. 16", listOf("Blue")),
        Station("S100", "Noida Sec. 18", listOf("Blue")),
        Station("S101", "Botanical Garden", listOf("Blue","Mergenta")),
        Station("S223", "Golf Course", listOf("Blue")),
        Station("S102", "Noida City Centre", listOf("Blue")),
        Station("S103", "Noida Sec. 34", listOf("Blue")),
        Station("S104", "Noida Sec. 52", listOf("Blue")),
        Station("S105", "Noida Sec. 61", listOf("Blue")),
        Station("S106", "Noida Sec. 59", listOf("Blue")),
        Station("S107", "Noida Sec. 62", listOf("Blue")),
        Station("S108", "Noida Electronic City", listOf("Blue")),

        Station("S109", "Laxmi Nagar", listOf("Blue")),
        Station("S110", "Nirman Vihar", listOf("Blue")),
        Station("S111", "Preet Vihar", listOf("Blue")),
        Station("S112", "Karkarduma", listOf("Blue","Pink")),
        Station("S113", "Anand Vihar ISBT", listOf("Blue","Pink")),
        Station("S114", "Kaushambi", listOf("Blue")),
        Station("S115", "Vaishali", listOf("Blue")),


//      Voilet Line

        Station("S116", "Lal Qila", listOf("Violet")),
        Station("S117", "Jama Masjid", listOf("Violet")),
        Station("S118", "Delhi Gate", listOf("Violet")),
        Station("S119", "ITO", listOf("Violet")),
//      mandi house
        Station("S120", "Janpath", listOf("Violet")),
//      central secretariate
        Station("S121", "Khan Market", listOf("Violet")),
        Station("S122", "JLN Stadium", listOf("Violet")),
        Station("S123", "Jangpura", listOf("Violet")),
        Station("S124", "Lajpat Nagar", listOf("Violet","Pink")),
        Station("S125", "Moolchand", listOf("Violet")),
        Station("S126", "Kailash Colony", listOf("Violet")),
        Station("S127", "Nehru Place", listOf("Violet")),
        Station("S128", "Kalkaji Mandir", listOf("Violet","Mergenta")),
        Station("S130", "Govindpuri", listOf("Violet")),
        Station("S131", "Harkesh Nagar Okhla", listOf("Violet")),
        Station("S132", "Jasola", listOf("Violet")),
        Station("S133", "Sarita Vihar", listOf("Violet")),
        Station("S134", "Mohan Estate", listOf("Violet")),
        Station("S135", "Tughlakabad", listOf("Violet")),
        Station("S136", "Badarpur", listOf("Violet")),
        Station("S137", "Sarai", listOf("Violet")),
        Station("S138", "NHPC Chowk", listOf("Violet")),
        Station("S139", "Mewala Maharajpur", listOf("Violet")),
        Station("S140", "Sector 28", listOf("Violet")),
        Station("S141", "Badkal Mor", listOf("Violet")),
        Station("S142", "Old Faridabad", listOf("Violet")),
        Station("S143", "Neelam Chowk Ajronda", listOf("Violet")),
        Station("S144", "Bata Chowk", listOf("Violet")),
        Station("S145", "Escort Mujesar", listOf("Violet")),
        Station("S146", "Sant Surdas (Sihi)", listOf("Violet")),
        Station("S147", "Raja Nahar Singh", listOf("Violet")),



//      Pink Line


        Station("S148", "Shiv Vihar", listOf("Pink")),
        Station("S149", "Johri Enclave", listOf("Pink")),
        Station("S150", "Gokulpuri", listOf("Pink")),
        Station("S151", "Maujpur - Babarpur", listOf("Pink")),
        Station("S152", "Jaffrabad", listOf("Pink")),
        //        welcome
        Station("S153", "East Azad Nagar", listOf("Pink")),
        Station("S154", "Krishna Nagar", listOf("Pink")),
        Station("S155", "Karkarduma Court", listOf("Pink")),
        //        karkarduma
        //        Anand Vihar ISBT
        Station("S156", "IP EXTN.", listOf("Pink")),
        Station("S157", "Mandawali - West Vinod Nagar", listOf("Pink")),
        Station("S158", "Vinod Nagar East - Mayur Vihar -II", listOf("Pink")),
        Station("S159", "Trilokpuri Sanjay Lake", listOf("Pink")),
        Station("S160", "Mayur Vihar PKT. 1", listOf("Pink")),
        //        Mayur Vihar 1
        Station("S161", "Sarai kale Khan Hazrat Nizamuddin", listOf("Pink")),
        Station("S162", "Ashram", listOf("Pink")),
        Station("S163", "Vinobapuri", listOf("Pink")),
//              Lajpat Nagar
        Station("S164", "South EXTN.", listOf("Pink")),
        //        INA
        Station("S165", "Sarojini Nagar", listOf("Pink")),
        Station("S166", "Bhikaji Cama Place", listOf("Pink")),
        Station("S167", "Sir Vishweshwaraiah Moti Bagh", listOf("Pink")),
        Station("S168", "Durgabai Deshmukh South Campus", listOf("Pink")),
        Station("S169", "Delhi Cantt.", listOf("Pink")),
        Station("S170", "Naraina Vihar", listOf("Pink")),
        Station("S171", "Mayapuri", listOf("Pink")),
        //        Rajouri Garden
        Station("S172", "ESI Basal Darapur", listOf("Pink")),
        Station("S173", "Panjabi Bagh West", listOf("Pink","Green")),
        Station("S174", "Shakurpur", listOf("Pink")),
        //        NSP
        Station("S175", "Shalimar Bagh", listOf("Pink")),
        //        Azadpur
        Station("S176", "Majlis Park", listOf("Pink")),



//        Mergenta line

        //  janakpuri west
        Station("S177", "Dabri More - Janakpuri South", listOf("Mergenta")),
        Station("S178", "Dashrath Puri", listOf("Mergenta")),
        Station("S179", "Palam", listOf("Mergenta")),
        Station("S180", "Sadar Bazar Contonment", listOf("Mergenta")),
        Station("S181", "terminal 1 - IGI Airport", listOf("Mergenta")),
        Station("S182", "Shankar Vihar", listOf("Mergenta")),
        Station("S183", "Vasant Vihar", listOf("Mergenta")),
        Station("S184", "Munirka", listOf("Mergenta")),
        Station("S185", "R.K.Puram", listOf("Mergenta")),
        Station("S186", "I.I.T", listOf("Mergenta")),
        //        Hauz Khas
        Station("S187", "Panchsheel park", listOf("Mergenta")),
        Station("S188", "Chirag Delhi", listOf("Mergenta")),
        Station("S189", "Greater Kailash", listOf("Mergenta")),
        Station("S190", "Nehru Enclave", listOf("Mergenta")),
        //        Kalkaji Mandir
        Station("S191", "Okhla NSIC ", listOf("Mergenta")),
        Station("S192", "Sukdev Vihar", listOf("Mergenta")),
        Station("S193", "Jamia Millia Islamia", listOf("Mergenta")),
        Station("S194", "Okhla Vihar", listOf("Mergenta")),
        Station("S195", "Jasola Vihar Shaheen Bagh", listOf("Mergenta")),
        Station("S196", "Kalindi Kunj", listOf("Mergenta")),
        Station("S197", "Okhla Bird Sanctuary", listOf("Mergenta")),
        //        Botanical Garden



//        Green Line

        // Inderlok
        Station("S198", "Ashok Park Main", listOf("Green")),
        Station("S199", "Panjabi Bagh", listOf("Green")),
        // Panjabi bagh west
        Station("S200", "Shivaji Park", listOf("Green")),
        Station("S224", "Madipur", listOf("Green")),
        Station("S201", "Paschim Vihar East", listOf("Green")),
        Station("S202", "Pashchim Vihar west", listOf("Green")),
        Station("S203", "Peeragarhi", listOf("Green")),
        Station("S204", "Udyog Nagar", listOf("Green")),
        Station("S205", "Surajmal Stadium", listOf("Green")),
        Station("S206", "Nangloi", listOf("Green")),
        Station("S207", "Nangloi Railway Station", listOf("Green")),
        Station("S208", "Rajdhani Park", listOf("Green")),
        Station("S209", "Mundka", listOf("Green")),
        Station("S210", "Mundka Industrial Area (MIA)", listOf("Green")),
        Station("S211", "Ghevra", listOf("Green")),
        Station("S212", "Tikri Kalan", listOf("Green")),
        Station("S213", "Tikri Border", listOf("Green")),
        Station("S214", "Pandit Shree Ram Sharma", listOf("Green")),
        Station("S215", "Bahadurgarh City", listOf("Green")),
        Station("S216", "Brigadier Hoshiar Singh", listOf("Green")),

        Station("S217", "Satguru Ram Singh Marg", listOf("Green")),


        )

    val connections = listOf(

        // Yellow Line
        Connection("S1", "S2", "Yellow", 3),
        Connection("S2", "S3", "Yellow", 3),
        Connection("S3", "S4", "Yellow", 3),
        Connection("S4", "S5", "Yellow", 3),
        Connection("S5", "S6", "Yellow", 3),
        Connection("S6", "S7", "Yellow", 3),
        Connection("S7", "S8", "Yellow", 3),
        Connection("S8", "S9", "Yellow", 3),
        Connection("S9", "S10", "Yellow", 3),
        Connection("S10", "S11", "Yellow", 3),
        Connection("S11", "S12", "Yellow", 3),
        Connection("S12", "S13", "Yellow", 3),
        Connection("S13", "S14", "Yellow", 3),
        Connection("S14", "S15", "Yellow", 3),
        Connection("S15", "S16", "Yellow", 3),
        Connection("S16", "S17", "Yellow", 3),
        Connection("S17", "S18", "Yellow", 3),
        Connection("S18", "S19", "Yellow", 3),
        Connection("S19", "S20", "Yellow", 3),
        Connection("S20", "S21", "Yellow", 3),
        Connection("S21", "S22", "Yellow", 3),
        Connection("S22", "S23", "Yellow", 3),
        Connection("S23", "S24", "Yellow", 3),
        Connection("S24", "S25", "Yellow", 3),
        Connection("S25", "S26", "Yellow", 3),
        Connection("S26", "S27", "Yellow", 3),
        Connection("S27", "S28", "Yellow", 3),
        Connection("S28", "S29", "Yellow", 3),
        Connection("S29", "S30", "Yellow", 3),
        Connection("S30", "S31", "Yellow", 3),
        Connection("S31", "S32", "Yellow", 3),
        Connection("S32", "S33", "Yellow", 3),
        Connection("S33", "S34", "Yellow", 3),
        Connection("S34", "S35", "Yellow", 3),
        Connection("S35", "S36", "Yellow", 3),
        Connection("S36", "S37", "Yellow", 3),


//        Red line

        Connection("S38", "S39", "Red", 3),
        Connection("S39", "S40", "Red", 3),
        Connection("S40", "S41", "Red", 3),
        Connection("S41", "S50", "Red", 3),
        Connection("S50", "S42", "Red", 3),
        Connection("S42", "S43", "Red", 3),
        Connection("S43", "S44", "Red", 3),
        Connection("S44", "S45", "Red", 3),
        Connection("S45", "S46", "Red", 3),
        Connection("S46", "S47", "Red", 3),
        Connection("S47", "S48", "Red", 3),
        Connection("S48", "S49", "Red", 3),
        Connection("S49", "S12", "Red", 3),
        Connection("S12", "S51", "Red", 3),
        Connection("S51", "S52", "Red", 3),
        Connection("S52", "S53", "Red", 3),
        Connection("S53", "S54", "Red", 3),
        Connection("S54", "S55", "Red", 3),
        Connection("S55", "S56", "Red", 3),
        Connection("S56", "S57", "Red", 3),
        Connection("S57", "S58", "Red", 3),
        Connection("S58", "S59", "Red", 3),
        Connection("S59", "S60", "Red", 3),
        Connection("S60", "S61", "Red", 3),
        Connection("S61", "S62", "Red", 3),
        Connection("S62", "S63", "Red", 3),
        Connection("S63", "S64", "Red", 3),
        Connection("S64", "S65", "Red", 3),


//        Blue line

        Connection("S66", "S69", "Blue", 3),
        Connection("S67", "S66", "Blue", 3),
        Connection("S68", "S67", "Blue", 3),
        Connection("S218", "S68", "Blue", 3),
        Connection("S219", "S218", "Blue", 3),
        Connection("S220", "S219", "Blue", 3),
        Connection("S221", "S220", "Blue", 3),
        Connection("S222", "S221", "Blue", 3),

        Connection("S69", "S70", "Blue", 3),
        Connection("S70", "S71", "Blue", 3),
        Connection("S71", "S72", "Blue", 3),
        Connection("S72", "S73", "Blue", 3),
        Connection("S73", "S74", "Blue", 3),
        Connection("S74", "S75", "Blue", 3),
        Connection("S75", "S76", "Blue", 3),
        Connection("S76", "S77", "Blue", 3),
        Connection("S77", "S78", "Blue", 3),
        Connection("S78", "S79", "Blue", 3),
        Connection("S79", "S80", "Blue", 3),
        Connection("S80", "S81", "Blue", 3),
        Connection("S81", "S82", "Blue", 3),
        Connection("S82", "S83", "Blue", 3),
        Connection("S83", "S84", "Blue", 3),
        Connection("S84", "S85", "Blue", 3),
        Connection("S85", "S86", "Blue", 3),
        Connection("S86", "S87", "Blue", 3),
        Connection("S87", "S88", "Blue", 3),
        Connection("S88", "S16", "Blue", 3),
        Connection("S16", "S89", "Blue", 3),
        Connection("S89", "S90", "Blue", 3),
        Connection("S90", "S91", "Blue", 3),
        Connection("S91", "S92", "Blue", 3),
        Connection("S92", "S93", "Blue", 3),

        Connection("S93", "S94", "Blue", 3),
        Connection("S94", "S95", "Blue", 3),
        Connection("S95", "S96", "Blue", 3),
        Connection("S96", "S97", "Blue", 3),
        Connection("S97", "S98", "Blue", 3),
        Connection("S98", "S99", "Blue", 3),
        Connection("S99", "S100", "Blue", 3),
        Connection("S100", "S101", "Blue", 3),
        Connection("S101", "S223", "Blue", 3),
        Connection("S223", "S102", "Blue", 3),
        Connection("S102", "S103", "Blue", 3),
        Connection("S103", "S104", "Blue", 3),
        Connection("S104", "S105", "Blue", 3),
        Connection("S105", "S106", "Blue", 3),
        Connection("S106", "S107", "Blue", 3),
        Connection("S107", "S108", "Blue", 3),


        Connection("S93", "S109", "Blue", 3),
        Connection("S109", "S110", "Blue", 3),
        Connection("S110", "S111", "Blue", 3),
        Connection("S111", "S112", "Blue", 3),
        Connection("S112", "S113", "Blue", 3),
        Connection("S113", "S114", "Blue", 3),
        Connection("S114", "S115", "Blue", 3),



        // violet line

        Connection("S12", "S116", "Violet", 3),
        Connection("S116", "S117", "Violet", 3),
        Connection("S117", "S118", "Violet", 3),
        Connection("S118", "S119", "Violet", 3),
        Connection("S119", "S90", "Violet", 3),
        Connection("S90", "S120", "Violet", 3),
        Connection("S120", "S18", "Violet", 3),
        Connection("S18", "S121", "Violet", 3),
        Connection("S121", "S122", "Violet", 3),
        Connection("S122", "S123", "Violet", 3),
        Connection("S123", "S124", "Violet", 3),
        Connection("S124", "S125", "Violet", 3),
        Connection("S125", "S126", "Violet", 3),
        Connection("S126", "S127", "Violet", 3),
        Connection("S127", "S128", "Violet", 3),
        Connection("S128", "S130", "Violet", 3),
        Connection("S130", "S131", "Violet", 3),
        Connection("S131", "S132", "Violet", 3),
        Connection("S132", "S133", "Violet", 3),
        Connection("S133", "S134", "Violet", 3),
        Connection("S134", "S135", "Violet", 3),
        Connection("S135", "S136", "Violet", 3),
        Connection("S136", "S137", "Violet", 3),
        Connection("S137", "S138", "Violet", 3),
        Connection("S138", "S139", "Violet", 3),
        Connection("S139", "S140", "Violet", 3),
        Connection("S140", "S141", "Violet", 3),
        Connection("S141", "S142", "Violet", 3),
        Connection("S142", "S143", "Violet", 3),
        Connection("S143", "S144", "Violet", 3),
        Connection("S144", "S145", "Violet", 3),
        Connection("S145", "S146", "Violet", 3),
        Connection("S146", "S147","Violet",3),


        //       Pink Line

        Connection("S148", "S149", "Pink", 3),
        Connection("S149", "S150", "Pink", 3),
        Connection("S150", "S151", "Pink", 3),
        Connection("S151", "S152", "Pink", 3),
        Connection("S152", "S53", "Pink", 3),
        Connection("S53", "S153", "Pink", 3),
        Connection("S153", "S154", "Pink", 3),
        Connection("S154", "S155", "Pink", 3),
        Connection("S155", "S112", "Pink", 3),
        Connection("S112", "S113", "Pink", 3),
        Connection("S113", "S156", "Pink", 3),
        Connection("S156", "S157", "Pink", 3),
        Connection("S157", "S158", "Pink", 3),
        Connection("S158", "S159", "Pink", 3),
        Connection("S159", "S160", "Pink", 3),
        Connection("S160", "S95", "Pink", 3),
        Connection("S95", "S161", "Pink", 3),
        Connection("S161", "S162", "Pink", 3),
        Connection("S162", "S163", "Pink", 3),
        Connection("S163", "S124", "Pink", 3),
        Connection("S124", "S164", "Pink", 3),
        Connection("S164", "S22", "Pink", 3),
        Connection("S22", "S165", "Pink", 3),
        Connection("S165", "S166", "Pink", 3),
        Connection("S166", "S167", "Pink", 3),
        Connection("S167", "S168", "Pink", 3),
        Connection("S168", "S169", "Pink", 3),
        Connection("S169", "S170", "Pink", 3),
        Connection("S170", "S171", "Pink", 3),
        Connection("S171", "S79", "Pink", 3),
        Connection("S79", "S172", "Pink", 3),
        Connection("S172", "S173", "Pink", 3),
        Connection("S173", "S174", "Pink", 3),
        Connection("S174", "S42", "Pink", 3),
        Connection("S42", "S175", "Pink", 3),
        Connection("S175", "S6", "Pink", 3),
        Connection("S6", "S176", "Pink", 3),



        //        Mergenta line

        Connection("S74", "S177", "Mergenta", 3),
        Connection("S177", "S178", "Mergenta", 3),
        Connection("S178", "S179", "Mergenta", 3),
        Connection("S179", "S180", "Mergenta", 3),
        Connection("S180", "S181", "Mergenta", 3),
        Connection("S181", "S182", "Mergenta", 3),
        Connection("S182", "S183", "Mergenta", 3),
        Connection("S183", "S184", "Mergenta", 3),
        Connection("S184", "S185", "Mergenta", 3),
        Connection("S185", "S186", "Mergenta", 3),
        Connection("S186", "S25", "Mergenta", 3),
        Connection("S25", "S187", "Mergenta", 3),
        Connection("S187", "S188", "Mergenta", 3),
        Connection("S188", "S189", "Mergenta", 3),
        Connection("S189", "S190", "Mergenta", 3),
        Connection("S190", "S128", "Mergenta", 3),
        Connection("S128", "S191", "Mergenta", 3),
        Connection("S191", "S192", "Mergenta", 3),
        Connection("S192", "S193", "Mergenta", 3),
        Connection("S193", "S194", "Mergenta", 3),
        Connection("S194", "S195", "Mergenta", 3),
        Connection("S195", "S196", "Mergenta", 3),
        Connection("S196", "S197", "Mergenta", 3),
        Connection("S197", "S101", "Mergenta", 3),



//        Green Line

        Connection("S45", "S198", "Green", 3),
        Connection("S198", "S199", "Green", 3),
        Connection("S199", "S173", "Green", 3),
        Connection("S173", "S200", "Green", 3),
        Connection("S200", "S201", "Green", 3),
        Connection("S201", "S202", "Green", 3),
        Connection("S202", "S203", "Green", 3),
        Connection("S203", "S204", "Green", 3),
        Connection("S204", "S205", "Green", 3),
        Connection("S205", "S206", "Green", 3),
        Connection("S206", "S207", "Green", 3),
        Connection("S207", "S208", "Green", 3),
        Connection("S208", "S209", "Green", 3),
        Connection("S209", "S210", "Green", 3),
        Connection("S210", "S211", "Green", 3),
        Connection("S211", "S212", "Green", 3),
        Connection("S212", "S213", "Green", 3),
        Connection("S213", "S214", "Green", 3),
        Connection("S214", "S215", "Green", 3),
        Connection("S215", "S216", "Green", 3),
        Connection("S198", "S217", "Green", 3),
        Connection("S217", "S82","Green",3),



        )

    return Pair(stations, connections)
}
